apiVersion: v1
kind: ConfigMap
metadata:
  name: occurrance-traker
data:
  application.yml: |
    spring:
      application:
        name: OccurenceTrakerApplication
    data:
      redis:
        host: redis-master.redis.svc.cluster.local
        port: 6379
