apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-cf-myorg--com
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  project: default
  sources:
  - repoURL: 'registry-1.docker.io/bitnamicharts'
    path: 'external-dns'
    targetRevision: 8.3.9
    chart: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
