apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentence-processor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/NHristovski/DevOpsAppOfApps.git
      path: sentence-processor
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
